# Image Modeling Configuration

dataset:
  name: image_modeling
  data_dir: data/imagenet1k_subset/
  image_size: 224
  batch_size: 32
  num_workers: 4
  pin_memory: true

model:
  name: linear_transformer_image
  num_classes: 1000
  hidden_size: 768
  num_layers: 12
  num_heads: 12
  ff_size: 3072
  dropout: 0.1
  patch_size: 16
  image_size: 224

trainer:
  learning_rate: 3e-5
  weight_decay: 1e-4
  max_epochs: 10
  device: cuda
  log_every_n_steps: 10
  save_every_n_steps: 100
  save_dir: checkpoints/
  mixed_precision: true
