# Machine Translation Configuration

dataset:
  name: machine_translation
  data_dir: data/wmt16_en_de/
  src_lang: en
  tgt_lang: de
  vocab_size: 32000
  max_seq_len: 128
  batch_size: 32
  num_workers: 4
  pin_memory: true

model:
  name: linear_transformer_translator
  vocab_size: 32000
  hidden_size: 512
  num_layers: 6
  num_heads: 8
  ff_size: 2048
  dropout: 0.1
  max_seq_len: 128
  pad_id: 0
  bos_id: 1
  eos_id: 2

trainer:
  learning_rate: 5e-5
  weight_decay: 1e-5
  max_epochs: 10
  device: cuda
  log_every_n_steps: 10
  save_every_n_steps: 100
  save_dir: checkpoints/
  mixed_precision: false
