# Speech Classification Configuration

dataset:
  name: speech_classification
  data_dir: data/sc10/
  n_mels: 80
  sample_rate: 16000
  batch_size: 32
  num_workers: 4
  pin_memory: true

model:
  name: linear_transformer_classifier
  num_classes: 10
  hidden_size: 256
  num_layers: 4
  num_heads: 4
  ff_size: 1024
  dropout: 0.1
  n_mels: 80

trainer:
  learning_rate: 1e-4
  weight_decay: 1e-5
  max_epochs: 10
  device: cuda
  log_every_n_steps: 10
  save_every_n_steps: 100
  save_dir: checkpoints/
  mixed_precision: false
